// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  firebase: {
    projectId: 'dndjarvis-ccc11',
    appId: '1:1098659875935:web:899cf86bb1dc1bffda5fea',
    storageBucket: 'dndjarvis-ccc11.appspot.com',
    apiKey: 'AIzaSyD1wMmQkxbf20f1tAzC02nRAVkLzN4tckE',
    authDomain: 'dndjarvis-ccc11.firebaseapp.com',
    messagingSenderId: '1098659875935',
    measurementId: 'G-RJD042CRFZ',
    databaseURL: 'https://dndjarvis-ccc11-default-rtdb.europe-west1.firebasedatabase.app'
  },
  production: true,
  version: env['npm_package_version'],
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US'],
};
